version: '3.5'

services:
  postgres:
    container_name: m3lody_db
    image: postgres
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: 1234rewqasdF
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./simple_schema.sql:/docker-entrypoint-initdb.d/simple_schema.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: